sudo: required
language: node_js
node_js:
- 8
- 9
- 10
python:
- 3.5
cache:
  pip: true
  yarn: true
  directories:
  - node_modules
before_install:
- sudo apt-get -y install python3-pip python-dev
- sudo pip3 install --upgrade setuptools
- sudo pip3 install therapist
- npm install -g coveralls
install:
- yarn install
after_success:
- yarn coverage
script:
- therapist run --use-tracked-files
- yarn test
deploy:
  provider: npm
  email: rehandalal@gmail.com
  on:
    tags: true
    repo: rehandalal/node-env-settings
  api_key:
    secure: l+IS+3tkezzgwO6gXMl9IS+IfLVweALzne4GkHj7fc3Al8dAsYuMBN4vB+sIJiUPS+IyXjs6h0gtse2q8QAek7hYqfUDJdPlZthhWFTAQIFTDisgSqXaTfUBFWYRS1vpeQHrRsb0kYuR3KzCwe8ovIUlaKGsSW6qPChVCT8y9J+5W3vTGUfKp0uwkySl1IraknXC8RDDubDkJP3Rc1qMji5B6HocGmEoEX5vjv3PZCQsWe30skp/CZZw7AJ9oeSJG08gImdCRAHF7rqfmBjgooLYyEuwTWhCe6HF/YE0Tx9yyLKCVXlj5sG9uKzpOk2DyjPB+WOKRoEBgWaFAU27N1wgC3TmQn2wXQNNnZlUjBP7i0VhOGyL9CrL3GT31/hX+I8tvtByexiF5+ySU8tJ+QnEQGQOoEFIBhd5TWz4xE4xnwQ1wXKHe2PIA1JK3EkdS+pbJAhC+Q8OtndSjjDcVvSgtDXv6VmG33qcXG4BZDz2EcwBPxmKiOf/CX6BHerlaN7lJabhmKbsoepKRaK/X5J0CPeH9zvA0oPZ9JaRxAeqogG4z8vYGvT6MR3GIqztaCaXg7BuDZRtRLHdNajDJsXBT8e39ufcMVJLhO2qyRsLhol9FOxD1l4KHsbGccfZTpdJFrR6ovBB65SQHBNOSsnJlSxJxnNWMLH0FXVrGu8=
