language: node_js
node_js:
- 8
- 9
- 10
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
- yarn install
script:
- yarn test
deploy:
  provider: npm
  email: rehandalal@gmail.com
  on:
    tags: true
    repo: rehandalal/node-env-settings
