sudo: required
language: node_js
node_js:
- 8
- 9
- 10
python:
- 3.5
cache:
  pip: true
  yarn: true
  directories:
  - node_modules
before_install:
- sudo apt-get -y install python3-pip python-dev
- sudo pip3 install --upgrade setuptools
- sudo pip3 install therapist
- npm install -g coveralls
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
- yarn install
after_success:
- yarn coverage
script:
- therapist run --use-tracked-files
- yarn test
deploy:
  provider: npm
  email: rehandalal@gmail.com
  on:
    tags: true
    repo: rehandalal/node-env-settings
